import transformerDirectives from '@unocss/transformer-directives'
import {defineConfig, presetWind3} from 'unocss'

export default defineConfig({
  presets: [presetWind3({preflight: false})],
  transformers: [transformerDirectives()],
  shortcuts: {
    'cv-u-row': 'flex items-center',
    'cv-u-row-between': 'flex items-center justify-between',
    'cv-u-inline-center': 'inline-flex items-center justify-center',
    'cv-u-stack-2': 'flex flex-col gap-2',
    'cv-u-stack-3': 'flex flex-col gap-3',
    'cv-u-control-shell': 'flex items-center gap-2',
    'cv-u-panel-shell': 'grid rounded-md border border-border bg-surface shadow-sm overflow-hidden',
    'cv-u-icon-slot': 'inline-flex items-center justify-center flex-shrink-0',
    'cv-u-fill': 'flex-1 min-w-0',
    'cv-u-clip': 'overflow-hidden',
  },
  blocklist: [
    'absolute',
    'b',
    'bg-surface',
    'block',
    'border',
    'border-border',
    'border-collapse',
    'backdrop-filter',
    'border-inline',
    'columns-2',
    'columns-3',
    'contents',
    'ease',
    'ease-in-out',
    'fixed',
    'flex',
    'flex-1',
    'flex-col',
    'flex-shrink',
    'flex-shrink-0',
    'flex-wrap',
    'gap-2',
    'gap-3',
    'grid',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hidden',
    'inline',
    'inline-block',
    'inline-flex',
    'inline-grid',
    'items-center',
    'justify-center',
    'justify-between',
    'lowercase',
    'min-w-0',
    'ms',
    'outline',
    'overflow-hidden',
    'p-4',
    'px',
    'relative',
    'resize',
    'ring',
    'rounded-md',
    'rounded-sm',
    'select-all',
    'shadow',
    'shadow-sm',
    'static',
    'sticky',
    'tab',
    'table',
    'table-cell',
    'table-header-group',
    'table-row',
    'table-row-group',
    'tabular-nums',
    'transform',
    'transition',
    'uppercase',
    'visible',
  ],
  content: {
    pipeline: {
      include: [/[/\\]src[/\\].*\.ts$/],
      exclude: [/[/\\]src[/\\]test[/\\]/, /\.test\.ts$/, /\.d\.ts$/],
    },
  },
  theme: {
    spacing: {
      1: 'var(--cv-space-1)',
      2: 'var(--cv-space-2)',
      3: 'var(--cv-space-3)',
      4: 'var(--cv-space-4)',
      5: 'var(--cv-space-5)',
      6: 'var(--cv-space-6)',
      7: 'var(--cv-space-7)',
      8: 'var(--cv-space-8)',
    },
    borderRadius: {
      sm: 'var(--cv-radius-sm)',
      md: 'var(--cv-radius-md)',
      lg: 'var(--cv-radius-lg)',
      xl: 'var(--cv-radius-xl)',
      pill: 'var(--cv-radius-pill)',
      full: 'var(--cv-radius-full)',
    },
    fontSize: {
      xs: ['var(--cv-font-size-xs)', {}],
      sm: ['var(--cv-font-size-sm)', {}],
      base: ['var(--cv-font-size-base)', {}],
      lg: ['var(--cv-font-size-lg)', {}],
      xl: ['var(--cv-font-size-xl)', {}],
      '2xl': ['var(--cv-font-size-2xl)', {}],
    },
    colors: {
      primary: 'var(--cv-color-primary)',
      accent: 'var(--cv-color-accent)',
      success: 'var(--cv-color-success)',
      warning: 'var(--cv-color-warning)',
      danger: 'var(--cv-color-danger)',
      surface: 'var(--cv-color-surface)',
      border: 'var(--cv-color-border)',
      text: {
        DEFAULT: 'var(--cv-color-text)',
        muted: 'var(--cv-color-text-muted)',
        subtle: 'var(--cv-color-text-subtle)',
      },
    },
    boxShadow: {
      sm: 'var(--cv-shadow-sm)',
      md: 'var(--cv-shadow-md)',
      lg: 'var(--cv-shadow-lg)',
      xl: 'var(--cv-shadow-xl)',
    },
    duration: {
      fast: 'var(--cv-duration-fast)',
      normal: 'var(--cv-duration-normal)',
      slow: 'var(--cv-duration-slow)',
    },
  },
})
