import {mkdir, readFile, readdir, writeFile} from 'node:fs/promises'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

import {componentItems} from '../docs/.vitepress/component-catalog.mjs'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(scriptDir, '..')
const specsDir = path.join(rootDir, 'specs', 'components')
const docsComponentsDir = path.join(rootDir, 'docs', 'components')

const autogeneratedBanner =
  '<!-- This file is auto-generated by scripts/prepare-docs.mjs. Do not edit directly. -->'

const writeStdout = (message) => {
  process.stdout.write(`${message}\n`)
}

function moveUsageSectionToTop(markdown) {
  const lines = markdown.split('\n')
  const usageStart = lines.findIndex((line) => line.trim() === '## Usage')
  if (usageStart === -1) return markdown

  let usageEnd = lines.length
  for (let index = usageStart + 1; index < lines.length; index += 1) {
    if (lines[index]?.startsWith('## ')) {
      usageEnd = index
      break
    }
  }

  const anatomyStart = lines.findIndex((line) => line.trim() === '## Anatomy')
  const insertIndex =
    anatomyStart === -1 ? lines.findIndex((line, index) => index > 0 && line.startsWith('## ')) : anatomyStart

  if (insertIndex === -1 || usageStart <= insertIndex) return markdown

  const usageSection = lines.slice(usageStart, usageEnd)
  const remaining = [...lines.slice(0, usageStart), ...lines.slice(usageEnd)]
  const before = remaining.slice(0, insertIndex)
  const after = remaining.slice(insertIndex)
  const result = [...before]

  if (result.at(-1)?.trim() !== '') {
    result.push('')
  }

  result.push(...usageSection)

  if (after[0]?.trim() !== '') {
    result.push('')
  }

  result.push(...after)

  return `${result.join('\n').replace(/\n{3,}/gu, '\n\n')}\n`
}

const specFiles = (await readdir(specsDir))
  .filter((file) => file.endsWith('.md') && file !== '_template.md')
  .map((file) => file.replace(/\.md$/u, ''))
  .sort()

const catalogSpecs = new Set(componentItems.map((item) => item.spec))
const missingFromCatalog = specFiles.filter((spec) => !catalogSpecs.has(spec))
const missingFromSpecs = componentItems.map((item) => item.spec).filter((spec) => !specFiles.includes(spec))

if (missingFromCatalog.length > 0 || missingFromSpecs.length > 0) {
  const details = [
    missingFromCatalog.length > 0 ? `catalog is missing specs: ${missingFromCatalog.join(', ')}` : null,
    missingFromSpecs.length > 0 ? `catalog references missing specs: ${missingFromSpecs.join(', ')}` : null,
  ]
    .filter(Boolean)
    .join('; ')

  throw new Error(`Docs component catalog is out of sync: ${details}`)
}

await mkdir(docsComponentsDir, {recursive: true})

for (const item of componentItems) {
  const outputPath = path.join(docsComponentsDir, `${item.slug}.md`)
  const specPath = path.join(specsDir, `${item.spec}.md`)
  const specContent = await readFile(specPath, 'utf8')
  const docsContent = moveUsageSectionToTop(specContent).trimEnd()

  const content = `${autogeneratedBanner}\n\n${docsContent}\n`
  await writeFile(outputPath, content, 'utf8')
}

writeStdout(`Prepared ${componentItems.length} component reference pages.`)
