import {mkdir, readdir, writeFile} from 'node:fs/promises'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

import {componentItems} from '../docs/.vitepress/component-catalog.mjs'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(scriptDir, '..')
const specsDir = path.join(rootDir, 'specs', 'components')
const docsComponentsDir = path.join(rootDir, 'docs', 'components')

const autogeneratedBanner =
  '<!-- This file is auto-generated by scripts/prepare-docs.mjs. Do not edit directly. -->'

const specFiles = (await readdir(specsDir))
  .filter((file) => file.endsWith('.md') && file !== '_template.md')
  .map((file) => file.replace(/\.md$/u, ''))
  .sort()

const catalogSpecs = new Set(componentItems.map((item) => item.spec))
const missingFromCatalog = specFiles.filter((spec) => !catalogSpecs.has(spec))
const missingFromSpecs = componentItems.map((item) => item.spec).filter((spec) => !specFiles.includes(spec))

if (missingFromCatalog.length > 0 || missingFromSpecs.length > 0) {
  const details = [
    missingFromCatalog.length > 0 ? `catalog is missing specs: ${missingFromCatalog.join(', ')}` : null,
    missingFromSpecs.length > 0 ? `catalog references missing specs: ${missingFromSpecs.join(', ')}` : null,
  ]
    .filter(Boolean)
    .join('; ')

  throw new Error(`Docs component catalog is out of sync: ${details}`)
}

await mkdir(docsComponentsDir, {recursive: true})

for (const item of componentItems) {
  const outputPath = path.join(docsComponentsDir, `${item.slug}.md`)
  const specPath = path.join(specsDir, `${item.spec}.md`)
  const relativeIncludePath = path.relative(path.dirname(outputPath), specPath).split(path.sep).join('/')

  const content = `${autogeneratedBanner}\n\n<!--@include: ${relativeIncludePath}-->\n`
  await writeFile(outputPath, content, 'utf8')
}

console.log(`Prepared ${componentItems.length} component reference pages.`)
