import {
  CVAccordion,
  CVAccordionItem,
  CVAlertDialog,
  CVAlert,
  CVBadge,
  CVBottomSheet,
  CVBreadcrumb,
  CVBreadcrumbItem,
  CVButton,
  CVButtonGroup,
  CVCallout,
  CVCard,
  CVCarousel,
  CVCarouselSlide,
  CVCheckbox,
  CVChip,
  CVChipGroup,
  CVCombobox,
  CVComboboxGroup,
  CVComboboxOption,
  CVCodeInput,
  CVCommandItem,
  CVCommandPalette,
  CVContextMenu,
  CVCopyButton,
  CVDateTimePicker,
  CVDatePicker,
  CVDialog,
  CVDisclosure,
  CVDropzone,
  CVDrawer,
  CVEmptyState,
  CVFeed,
  CVFeedArticle,
  CVField,
  CVFieldset,
  CVGrid,
  CVGridCell,
  CVGridColumn,
  CVGridRow,
  CVGuidanceAnchor,
  CVGuidancePanel,
  CVIcon,
  CVImageViewer,
  CVInput,
  CVKbd,
  CVLandmark,
  CVLink,
  CVListbox,
  CVListboxGroup,
  CVMenu,
  CVMenuButton,
  CVMenuGroup,
  CVMenuItem,
  CVMeter,
  CVNumber,
  CVOption,
  CVOperationQueue,
  CVPagination,
  CVPopover,
  CVProgress,
  CVProgressRing,
  CVRadio,
  CVRadioGroup,
  CVSelect,
  CVSelectGroup,
  CVSelectOption,
  CVShortcut,
  CVSidebar,
  CVSidebarItem,
  CVSlider,
  CVSliderMultiThumb,
  CVSkeleton,
  CVSpinbutton,
  CVSpinner,
  CVStatusIndicator,
  CVStep,
  CVSteps,
  CVSwitch,
  CVTab,
  CVTabPanel,
  CVTable,
  CVTableCell,
  CVTableColumn,
  CVTableRow,
  CVTabs,
  CVTextarea,
  CVTimePicker,
  CVToast,
  CVToastRegion,
  CVTaskList,
  CVToolbar,
  CVToolbarItem,
  CVToolbarSeparator,
  CVTooltip,
  CVTreegrid,
  CVTreegridCell,
  CVTreegridColumn,
  CVTreegridRow,
  CVTreeItem,
  CVTreeview,
  CVWindowSplitter,
} from './components/index'
import {CVThemeProvider} from './theme/index'

export function registerUikit(): void {
  CVThemeProvider.define()
  CVAccordionItem.define()
  CVAccordion.define()
  CVAlertDialog.define()
  CVAlert.define()
  CVBreadcrumbItem.define()
  CVBreadcrumb.define()
  CVBadge.define()
  CVBottomSheet.define()
  CVButton.define()
  CVButtonGroup.define()
  CVCallout.define()
  CVCard.define()
  CVCopyButton.define()
  CVCarouselSlide.define()
  CVCarousel.define()
  CVCheckbox.define()
  CVChip.define()
  CVChipGroup.define()
  CVCommandItem.define()
  CVCommandPalette.define()
  CVComboboxGroup.define()
  CVComboboxOption.define()
  CVCombobox.define()
  CVCodeInput.define()
  CVContextMenu.define()
  CVDateTimePicker.define()
  CVDatePicker.define()
  CVDialog.define()
  CVDisclosure.define()
  CVDropzone.define()
  CVDrawer.define()
  CVEmptyState.define()
  CVFeedArticle.define()
  CVFeed.define()
  CVField.define()
  CVFieldset.define()
  CVGridCell.define()
  CVGridColumn.define()
  CVGridRow.define()
  CVGrid.define()
  CVGuidanceAnchor.define()
  CVGuidancePanel.define()
  CVIcon.define()
  CVImageViewer.define()
  CVInput.define()
  CVKbd.define()
  CVLandmark.define()
  CVOption.define()
  CVListboxGroup.define()
  CVListbox.define()
  CVLink.define()
  CVMenuItem.define()
  CVMenuGroup.define()
  CVMenu.define()
  CVMenuButton.define()
  CVMeter.define()
  CVNumber.define()
  CVOperationQueue.define()
  CVPagination.define()
  CVPopover.define()
  CVProgress.define()
  CVProgressRing.define()
  CVRadio.define()
  CVRadioGroup.define()
  CVSelectOption.define()
  CVSelectGroup.define()
  CVSelect.define()
  CVShortcut.define()
  CVSidebarItem.define()
  CVSidebar.define()
  CVSlider.define()
  CVSliderMultiThumb.define()
  CVSkeleton.define()
  CVSpinbutton.define()
  CVSpinner.define()
  CVStatusIndicator.define()
  CVStep.define()
  CVSteps.define()
  CVSwitch.define()
  CVTableCell.define()
  CVTableColumn.define()
  CVTableRow.define()
  CVTable.define()
  CVTab.define()
  CVTabPanel.define()
  CVTabs.define()
  CVTextarea.define()
  CVTimePicker.define()
  CVToast.define()
  CVToastRegion.define()
  CVTaskList.define()
  CVToolbarSeparator.define()
  CVToolbarItem.define()
  CVToolbar.define()
  CVTooltip.define()
  CVTreegridColumn.define()
  CVTreegridCell.define()
  CVTreegridRow.define()
  CVTreegrid.define()
  CVTreeItem.define()
  CVTreeview.define()
  CVWindowSplitter.define()
}
