import {describe, expect, it} from 'vitest'

import {registerUikit} from './register'

const registeredElements = [
  'cv-accordion',
  'cv-accordion-item',
  'cv-alert',
  'cv-alert-dialog',
  'cv-badge',
  'cv-bottom-sheet',
  'cv-breadcrumb',
  'cv-breadcrumb-item',
  'cv-button',
  'cv-button-group',
  'cv-callout',
  'cv-card',
  'cv-carousel',
  'cv-carousel-slide',
  'cv-checkbox',
  'cv-chip',
  'cv-chip-group',
  'cv-combobox',
  'cv-combobox-group',
  'cv-combobox-option',
  'cv-code-input',
  'cv-command-item',
  'cv-command-palette',
  'cv-context-menu',
  'cv-copy-button',
  'cv-date-time-picker',
  'cv-date-picker',
  'cv-dialog',
  'cv-disclosure',
  'cv-dropzone',
  'cv-drawer',
  'cv-empty-state',
  'cv-feed',
  'cv-feed-article',
  'cv-field',
  'cv-fieldset',
  'cv-grid',
  'cv-grid-cell',
  'cv-grid-column',
  'cv-grid-row',
  'cv-guidance-anchor',
  'cv-guidance-panel',
  'cv-icon',
  'cv-input',
  'cv-kbd',
  'cv-landmark',
  'cv-link',
  'cv-listbox',
  'cv-listbox-group',
  'cv-menu',
  'cv-menu-button',
  'cv-menu-group',
  'cv-menu-item',
  'cv-meter',
  'cv-number',
  'cv-option',
  'cv-operation-queue',
  'cv-pagination',
  'cv-popover',
  'cv-progress',
  'cv-progress-ring',
  'cv-radio',
  'cv-radio-group',
  'cv-select',
  'cv-select-group',
  'cv-select-option',
  'cv-shortcut',
  'cv-sidebar',
  'cv-sidebar-item',
  'cv-slider',
  'cv-slider-multi-thumb',
  'cv-skeleton',
  'cv-spinner',
  'cv-status-indicator',
  'cv-step',
  'cv-steps',
  'cv-switch',
  'cv-tab',
  'cv-tab-panel',
  'cv-table',
  'cv-table-cell',
  'cv-table-column',
  'cv-table-row',
  'cv-tabs',
  'cv-textarea',
  'cv-time-picker',
  'cv-toast',
  'cv-toast-region',
  'cv-task-list',
  'cv-toolbar',
  'cv-toolbar-item',
  'cv-toolbar-separator',
  'cv-tooltip',
  'cv-treegrid',
  'cv-treegrid-cell',
  'cv-treegrid-column',
  'cv-treegrid-row',
  'cv-treeitem',
  'cv-treeview',
  'cv-window-splitter',
] as const

describe('registerUikit', () => {
  it('registers the full custom element surface', () => {
    registerUikit()

    for (const tagName of registeredElements) {
      expect(customElements.get(tagName), `${tagName} should be registered`).toBeTruthy()
    }
  })
})
